name: bundle

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - dist/**
  schedule:
    - cron: 30 3 */3 * *
  workflow_dispatch:

permissions:
  actions: read
  contents: write

concurrency:
  group: ${{ github.workflow }}

jobs:
  bundle:
    uses: uikawinwing/tavern_helper_toolchain/.github/workflows/consumer-bundle.yaml@main
